import test from 'node:test';
import assert from 'node:assert/strict';
import {Graph,CATALOG,compile,evaluate,experiment,totalGraphs,fromMask,toMask} from '../public/engine.js';
import {oracle} from '../oracle.mjs';
import {verify} from '../verify.mjs';

test('safe expression language handles precedence, comparisons and parentheses',()=>{const get=oracle(3,3);assert.equal(evaluate(compile('connected AND (edges == 2 || complete)'),get),true);assert.equal(evaluate(compile('NOT complete && diameter >= 2'),get),true);assert.equal(evaluate(compile('acyclic && girth == infinity'),get),true);for(const bad of ['edges','connected;fetch("x")','constructor.constructor','connected &&','unknown','edges > connected','(connected','true false'])assert.throws(()=>compile(bad),undefined,bad);});
test('all 33,867 labeled graphs through six vertices match independent core oracles',()=>{const names=['connected','bipartite','triangle_free','acyclic','tree','regular','complete','even_degrees','no_isolates','eulerian','components','min_degree','max_degree','edges','vertices'];let tested=0;for(let n=1;n<=6;n++)for(let mask=0;mask<2**(n*(n-1)/2);mask++){const graph=new Graph(n,mask),get=oracle(n,mask);for(const name of names)assert.equal(graph.get(name),get(name),`${name}: n=${n}, mask=${mask}`);tested++;}assert.equal(tested,33867);});
test('all properties match independent oracles for every graph through n=5 plus reproducible n=6 sample',()=>{for(let n=1;n<=6;n++)for(let mask=0;mask<2**(n*(n-1)/2);mask+=n===6?127:1){const graph=new Graph(n,mask),get=oracle(n,mask);for(const name of Object.keys(CATALOG))assert.equal(graph.get(name),get(name),`${name}: n=${n}, mask=${mask}`);}});
test('the smallest triangle-free nonbipartite witness is a chordless five-cycle',async()=>{const result=await experiment({antecedent:'triangle_free',consequent:'bipartite',maxVertices:6,mode:'first'});assert.equal(result.status,'counterexample');assert.equal(result.witness.n,5);assert.equal(result.witness.edges.length,5);assert.equal(result.witness.properties.girth,5);assert.equal(result.witness.properties.chromatic_number,3);assert.equal(result.witness.details.oddCycle.length,5);assert.equal(verify(result).verified,true);});
test('no isolated vertices does not imply connected: two edges on four vertices',async()=>{const r=await experiment({antecedent:'no_isolates',consequent:'connected',maxVertices:6,mode:'first'});assert.equal(r.witness.n,4);assert.equal(r.witness.edges.length,2);assert.equal(r.witness.properties.components,2);assert.equal(verify(r).verified,true);});
test('connected even-degree graphs satisfy the constructive Euler test throughout the complete n<=6 census',async()=>{const r=await experiment({antecedent:'connected && even_degrees',consequent:'eulerian',maxVertices:6,mode:'census'});assert.equal(r.status,'bounded');assert.equal(r.complete,true);assert.equal(r.counts.checked,totalGraphs(6));assert.equal(r.counts.violations,0);assert.equal(verify(r).verified,true);assert.match(r.claim,/not a proof/);});
test('minimum degree two still allows a bridge: two triangles joined by an edge',async()=>{const r=await experiment({antecedent:'connected && min_degree >= 2',consequent:'bridgeless',maxVertices:6,mode:'first'});assert.equal(r.witness.n,6);assert.equal(r.witness.edges.length,7);assert.equal(r.witness.details.bridges.length,1);assert.equal(verify(r).verified,true);});
test('editing, encoding and replay are deterministic',()=>{for(let n=1;n<=6;n++)for(let mask=0;mask<2**(n*(n-1)/2);mask+=113)assert.equal(toMask(n,fromMask(n,mask)),mask);const cycle=new Graph(5,toMask(5,[[0,1],[1,2],[2,3],[3,4],[4,0]]));assert.equal(cycle.get('bipartite'),false);const path=new Graph(5,toMask(5,cycle.edges.slice(0,-1)));assert.equal(path.get('bipartite'),true);});
test('cancel returns partial evidence and is never called bounded verification',async()=>{let cancel=false;const r=await experiment({antecedent:'true',consequent:'vertices <= 6',maxVertices:6,mode:'census'},{progress:()=>{cancel=true;},cancelled:()=>cancel});assert.equal(r.status,'cancelled');assert.equal(r.complete,false);assert.equal(r.counts.checked,256);assert.throws(()=>verify(r),/Cancelled/);});
test('certificate verification rejects tampered counts and invented witnesses',async()=>{const r=await experiment({antecedent:'triangle_free',consequent:'bipartite',maxVertices:6,mode:'first'});const counts=structuredClone(r);counts.counts.checked++;assert.throws(()=>verify(counts),/mismatch/);const witness=structuredClone(r);witness.witness.mask++;assert.throws(()=>verify(witness),/not the first/);const props=structuredClone(r);props.witness.properties.bipartite=true;assert.throws(()=>verify(props),/incorrect/);});
test('a premise that never holds is reported as a vacuous finite check',async()=>{const r=await experiment({antecedent:'vertices > 6',consequent:'false',maxVertices:3,mode:'census'});assert.equal(r.counts.eligible,0);assert.match(r.claim,/vacuously/);assert.equal(verify(r).verified,true);});
test('structural and narrative tampering is rejected',async()=>{const r=await experiment({antecedent:'triangle_free',consequent:'bipartite',maxVertices:6,mode:'first'});const cycle=structuredClone(r);cycle.witness.details.oddCycle=[0,1,2];assert.throws(()=>verify(cycle),/odd cycle/);const bridge=structuredClone(r);bridge.witness.details.bridges=[[0,1]];assert.throws(()=>verify(bridge),/Bridge/);const claim=structuredClone(r);claim.claim='This proves all graphs satisfy the conjecture.';assert.throws(()=>verify(claim),/claim was modified/);});
